# Generated by Django 4.0.5 on 2023-11-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=50)),
                ('semail', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('fee', models.DecimalField(decimal_places=0, max_digits=9)),
            ],
        ),
    ]
